#include "Public.h"
#include <netdb.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>

// additional imports
#include <unistd.h>
#include <arpa/inet.h>

#define SA struct sockaddr

struct Person alice;

void chat_with_server(int sockfd)
{
    int bob_public_key;

    // character buffer for message string
    char buff[MAX];
    int N;

    alice.public_key = mod_exp(g, alice.private_key, n);

    // zero out the buffer
    memset(buff, '\0', sizeof(buff));
    N = 0;

    // set Alice's public key to the outgoing buffer
    printf("Sending Alice's public key to Bob... %d\n", alice.public_key);
    sprintf(buff, "%d", alice.public_key);

    // send public key to Bob
    write(sockfd, buff, sizeof(buff));
    printf("Sent Alice's public key to Bob... %d\n", alice.public_key);

    // zero out the buffer
    memset(buff, '\0', sizeof(buff));

    // read public key from Bob
    read(sockfd, buff, sizeof(buff));
    bob_public_key = atoi(buff);
    printf("Received Bob's public key: %d\n", bob_public_key);

    // calculate shared secret
    alice.shared_secret = mod_exp(bob_public_key, alice.private_key, n);
    printf("Shared secret generated by Alice: %d\n", alice.shared_secret);

    printf("Key exchange complete\n\n");
}

int main()
{
    int sockfd, connfd;
    struct sockaddr_in servaddr, cli;

    printf("Hello from Alice");
    alice.private_key = 1523;

    // socket create and varification
    sockfd = socket(AF_INET, SOCK_STREAM, 0);
    if (sockfd == -1)
    {
        printf("socket creation failed...\n");
        exit(0);
    }
    else
        printf("Socket successfully created..\n");
    bzero(&servaddr, sizeof(servaddr));

    // assign IP, PORT
    servaddr.sin_family = AF_INET;
    servaddr.sin_addr.s_addr = inet_addr("127.0.0.1");
    servaddr.sin_port = htons(PORT);

    // connect the client socket to server socket
    if (connect(sockfd, (SA *)&servaddr, sizeof(servaddr)) != 0)
    {
        printf("connection with the server failed...\n");
        exit(0);
    }
    else
        printf("connected to the server..\n");

    // function for chat
    chat_with_server(sockfd);

    // close the socket
    close(sockfd);
}
