#include "Public.h"

#include <stdio.h>
#include <netdb.h>
#include <netinet/in.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <sys/types.h>

// additional imports
#include <unistd.h>
#include <arpa/inet.h>

#define SA struct sockaddr

struct Person bob;

// Function designed for chat between client and server.
void chat_with_client(int sockfd)
{
    char buff[MAX];
    int alice_public_key;
    int N;

    // zero out the buffer
    memset(buff, '\0', MAX);

    // read the message from client and copy it in buffer
    read(sockfd, buff, sizeof(buff));

    // Convert value for Alice's public key
    alice_public_key = atoi(buff);
    printf("Received Alice's public key: %d\n", alice_public_key);

    // set Bob's public key
    bob.public_key = mod_exp(g, bob.private_key, n);

    // zero out the buffer
    memset(buff, '\0', MAX);
    N = 0;

    // set Bob's public key to the outgoing buffer
    sprintf(buff, "%d", bob.public_key);

    // and send that buffer to client
    printf("Sending Bob's public key to Alice... %d\n", bob.public_key);
    write(sockfd, buff, sizeof(buff));
    printf("Sent Bob's public key to Alice... %d\n", bob.public_key);

    // calculate shared secret
    bob.shared_secret = mod_exp(alice_public_key, bob.private_key, n);
    printf("Shared secret generated by Bob: %d", bob.shared_secret);

    printf("Key exchange complete\n\n");
}

// Driver function
int main()
{
    // define bob's member variables
    printf("Hello from Bob\n");
    bob.private_key = 1597;

    int sockfd, connfd, len;
    struct sockaddr_in servaddr, cli;

    // socket create and verification
    sockfd = socket(AF_INET, SOCK_STREAM, 0);
    if (sockfd == -1)
    {
        printf("socket creation failed...\n");
        exit(0);
    }
    else
        printf("Socket successfully created..\n");
    bzero(&servaddr, sizeof(servaddr));

    // assign IP, PORT
    servaddr.sin_family = AF_INET;
    servaddr.sin_addr.s_addr = htonl(INADDR_ANY);
    servaddr.sin_port = htons(PORT);

    // Binding newly created socket to given IP and verification
    if ((bind(sockfd, (SA *)&servaddr, sizeof(servaddr))) != 0)
    {
        printf("socket bind failed...\n");
        exit(0);
    }
    else
        printf("Socket successfully binded..\n");

    // Now server is ready to listen and verification
    if ((listen(sockfd, 5)) != 0)
    {
        printf("Listen failed...\n");
        exit(0);
    }
    else
        printf("Server listening..\n");
    len = sizeof(cli);

    // Accept the data packet from client and verification
    connfd = accept(sockfd, (SA *)&cli, &len);
    if (connfd < 0)
    {
        printf("server acccept failed...\n");
        exit(0);
    }
    else
        printf("server acccept the client...\n");

    // Function for chatting between client and server
    chat_with_client(connfd);

    // After chatting close the socket
    close(sockfd);
}
